package ho.unit4;

public class methods {

	public static void printSignature() {

		System.out.println("\r\n" + 
				"██╗  ██╗███████╗██╗   ██╗██╗███╗   ██╗    ██╗  ██╗ ██████╗ \r\n" + 
				"██║ ██╔╝██╔════╝██║   ██║██║████╗  ██║    ██║  ██║██╔═══██╗\r\n" + 
				"█████╔╝ █████╗  ██║   ██║██║██╔██╗ ██║    ███████║██║   ██║\r\n" + 
				"██╔═██╗ ██╔══╝  ╚██╗ ██╔╝██║██║╚██╗██║    ██╔══██║██║   ██║\r\n" + 
				"██║  ██╗███████╗ ╚████╔╝ ██║██║ ╚████║    ██║  ██║╚██████╔╝\r\n" + 
				"╚═╝  ╚═╝╚══════╝  ╚═══╝  ╚═╝╚═╝  ╚═══╝    ╚═╝  ╚═╝ ╚═════╝ \r\n" + 
				"                                                           \r\n" + 
				"");
	
	}
	
	public static void printImage() {
		
		System.out.println("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmdhhdmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmdhhhsso++oooossyyhddmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmdhyyso++oso+ooo++ooooossssssyyyhhhdmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMNNNmhysssso++++++++ooooosso+++oooooossssssoo+++osyyhddmNNNMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMNNmdhso++o++++o+++/++oo++++ooooo+oossoooooo+osysssoo++++ossssssyyhhdddmNMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMmhyso+///++ossssso++++ooo+/++++++ooo++++++++oo++++oosooo++ossssssssoooshdmNMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMh+++++oosssoo+/++oooooooooossso++/+oso++++oooooooooooo+ooooooooossyddmNNNNNMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMd++++++oooo++++++//++o+//+++ooo++oooooooooo++ooo++++ooosso++oshdmNNNNNNNNNNMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMN++oo+/+ooooo+ooo+//++++++++////+++oooo+ooooossooooooosyyhddmNNNNNNNNNNNNMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMM//hy+/++++ohhsoooo//+//++oooooo++////++++/+ossssossyhdNNNNNNNNNNNNNMNNNMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMyshmo:+oo++mmsooooo++++oooooooooo+++++o++////+shdmNNNNNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMmmhyyysysoodmyooysss+////+oooooooosss++++oyhdNNNNNNNMMNNNNNNNNNNNNMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMdyhhhdmmmoodmyoommoo+/////++ooooooyyy+++NNNNNNNNNNNNMMNNMMNNNNNNMMMMNMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMmyyhhsysysohmmddmms+++//////ossooooosoooNNNNNNNNNNNNMMNNMMNNMMNMMMMMNMMNNMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMNhhmdsso+dmhyhddmmysshy+//::smdsooooooooNNNNNNNNNNNNMMMMMMNMMMMMMMMMMMMNMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMNosddyssshdhsyhhhhhhymmyoohyydmyssssshyyNNNMMNNNMNNNMMMMMMMMMMMMMMMMNMMNMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMsohhhhhyyhhsydddhdmmmmdysdmdhhddhyssmmmNNMMMMMMMNNMMNMMMMMMMMMNNMMNMNNNMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMdhhhyyhhyoshydmmmmmmddmmmyyhhhdmmmmmhddNMMMMMMNNMMMNMMMMMMMMNNNNMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMdyhhy++oosshhhhssyhdhhhhdhhhhhysymmmhhdMMMMMNNNNMMMNMMMNNNNMNNNNMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMmyhhhhyooysyyhhyo+++hhhyhmmdhhyysdmmhhdMNMMMNNNNMMNMMMNNNNMMMNMMMMMMMNMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMNhhyhdhyyhhyshhhhhsohhy++osyhhhhhhddyydNNMMMNNNMNNMMMMMMNNMMNNMMNNNNNMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMNhhyymmhhhhyyhhdddyydmdsoo+ohhyyyhhh++sMMMMMMMMMNNNNMMMMMMNNMMMNNNNNNMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMhhyyhdsyhhdmdddmmhhhhhssssshhysshhhoosNNMMMMNNNNNNNMMMMMMMMMMMMNNNMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMhyhhhhsoooydddmhdhhhyyssyyyhhhhhyhhssyNNMMNNNNNMMNNMMMMMMNNNNMMMNNNNNMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMmhddhhyyssshyosyhhhhhhyyhhhhhhhhysyssyNMMMNNNNNMMMMMMMMMMNNNNMMMMNNNNMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMmdddhyhhyysosysyydmhyyhhhhhyyhhhddhyyhMMMMMMMNMMMMMNNNNMMNNNMMMMNNNNNMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMmhhyhhhhhyysshhyyhdhoooshdhooosydmmhhdNNMMMMMMMNNMMNNNNMMMMMMMMMNNNNMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMNyyhhddhdhyyyooyyyhyssooymmssooohhdyhdNMNNMMMNNNNNNMMNMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMyyddddsyddhhssyhhhhyyyyyddhyysssyhyyhMMNNMMNNNNNNNNNMMMMMNNNNMMNMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMmdddsssshdmdhyyyhhhdhhhhhhmmhyysoshhdMMNNMMMNNNNNNNNNMMNNMMMMNMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMNdyhyyydmdhddhhhmmhhhhhdddyyhhydddMMMMMMMMMNNMMNNMNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMNmhddyyhmdosydyosmddhhhhyyhmmmNNMMMNMMMMMMMMMMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMNdyydhssooyhydmdhhyhsoosydMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmhyyshdhyyhhhoosssooyMMMNMMNNNMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmdhddhhhhhhyyyyyyhMMNMMMNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmdyyyhhyyyyydMNMMMNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdhyyhhhyydNNMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmmddmmmNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\r\n" + 
				"");
		
	}
	
	public static void main(String[] args) {
		
		printSignature();
		printImage();
		
	}

}
